name: Build and Test Packages

on:
  pull_request:
    branches: ['*']
  workflow_call:
    outputs:
      build-run-id:
        value: ${{ jobs.build.outputs.run-id }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    needs:
      - build
    permissions:
      actions: read
    with:
      build-run-id: ${{ needs.build.outputs.run-id }}
